const sendgrid = require('@sendgrid/mail')

const jobName = 'email'
// API Key ID: mfQn087YRgSDNPfz07EGIw
const SENDGRID_API_KEY = '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'
sendgrid.setApiKey(SENDGRID_API_KEY)

class EmailJob {
  constructor(message) {
    this.name = jobName
    this.message = message
  }

  enqueue(queue) {
    console.log(this.name, this.message)
    return queue.add(this.name, {message: this.message})
  }
}

const handleJob = async (job) => {
  console.log(`Begin ${jobName} handler`)
  const msg = {
    to: 'ron@luminopia.com',
    from: 'noreply@luminopia.com',
    subject: 'Test email (generated by bull-demo)',
    text: job.data.message,
  };
  await sendgrid.send(msg)
  console.log(`End ${jobName} handler`)
}

module.exports = {
  EmailJob,
  jobName,
  handleJob,
}
